WIP:Ws
hackathon-22-winter-01/hackathon-22-winter-01_backend pull request #15
Opened 2022-12-13 10:15 UTC by tesso57

- close #1

2022-12-13 13:07 UTC, ras0q requested changes
まだ全部見てないけど、理解が天才

2022-12-13 13:07 UTC, ras0q commented on internal/handler/handler.go
> +	return echo.NewHTTPError(http.StatusNoContent)
c.NoContent使うのがいいです

2022-12-13 13:07 UTC, ras0q commented on internal/handler/handler.go
>  }
streamer使われてない

2022-12-13 13:07 UTC, ras0q commented on internal/usecases/services/ws/ws.go
> +package ws
ファイル名わかりにくいからstreamer.goの方がよさ

2022-12-13 13:40 UTC, tesso57 commented
```
echo: http: response.WriteHeader on hijacked connection from github.com/labstack/echo/v4.(*Response).WriteHeader (response.go:63)
```
このエラーがいまいちわからずになってる

2022-12-13 13:49 UTC, ras0q commented
原因はこれで、ServeWsする前に204書き込むと治りそう
エラーの時はふつうにecho.HTTPError返してよさそう

https://scrapbox.io/ras0q/gorilla%2Fwebsocketでresponse.WriteHeader_on_hijacked_connection

2022-12-13 15:22 UTC, ras0q reviewed
ちょっとだけ🙏
returnの前1行開けてるのってlinter？

2022-12-13 15:22 UTC, ras0q commented on go.mod
> +	github.com/gorilla/websocket v1.5.0 // indirect
indirectじゃなさそう
go mod tidyしてみて

2022-12-13 15:22 UTC, ras0q commented on internal/handler/handler.go
> +	// c.Response().WriteHeader(http.StatusNoContent)
コメント外し忘れてる？

2022-12-13 15:22 UTC, ras0q commented on internal/handler/handler.go
>  	// TODO: (usecases/service/ws).ServeWsを読んで、websocketの接続を確立する
要らなくなったら消してok

2022-12-13 15:22 UTC, ras0q commented on internal/usecases/services/ws/client.go
> +// reads from this goroutine.
ここら辺のコメントも消して良さそう

2022-12-13 15:22 UTC, ras0q commented on internal/usecases/services/ws/client.go
> +// executing all writes from this goroutine.
ここも

2022-12-13 15:22 UTC, ras0q commented on internal/usecases/services/ws/client.go
> +		}
ここら辺エラー受け取ったらログはいてreturnしてるので、そもそもの返り値をerrorにしてwritepump呼んだとこでログ吐くのが良さそう

2022-12-13 15:39 UTC, ras0q commented
Writeheaderってしなくてもよさそう？
コメントアウト外すって意味で言ってた🙏

2022-12-13 15:52 UTC, ras0q requested changes

2022-12-13 15:52 UTC, ras0q commented on internal/usecases/services/ws/streamer.go
> +	go client.writePump()
errorが帰ってくるようになったのでエラーハンドリングして欲しい🙏

go func () {
if err ~~~~ {
logger.Error(err)
}
}

2022-12-13 15:52 UTC, ras0q commented on internal/usecases/services/ws/streamer.go
> +	if err := eg.Wait(); err != nil {
これだとwritepumpのforループ終わるまで待っちゃうので↓みたいに書くと良さそう
```
go func() {
  if err := c.writepump(); err != nil {
    c.logger.Error(err)
  }
}
```

2022-12-13 16:01 UTC, tesso57 commented
> returnの前1行開けてるのってlinter？

そうそう。めっちゃ怒られた。

2022-12-13 16:11 UTC, ras0q commented
気になるなら.golangci.ymlからnlreturn外してもおっけー

2022-12-14 06:07 UTC, ras0q requested changes
ちょっとだけ

2022-12-14 13:31 UTC, ras0q reviewed
ここだけ:pray:

2022-12-14 13:31 UTC, ras0q commented on internal/usecases/services/ws/client.go
> +		}
```suggestion
		if err := client.conn.ReadJSON(req); err != nil {
			if !websocket.IsCloseError(err) && !websocket.IsUnexpectedCloseError(err) {
				return err
			}
		}
```

2022-12-14 13:31 UTC, ras0q commented on internal/usecases/services/ws/client.go
> +		}
```suggestion
		if err := client.callEventHandler(req); err != nil {
			return err
		}
```

2022-12-14 13:31 UTC, ras0q commented on internal/usecases/services/ws/client.go
> +		client.logger.Error("error:", err.Error())
```suggestion
		return err
```

2022-12-14 13:37 UTC, ras0q approved these changes

2022-12-14 13:38 UTC, merged