Room
hackathon-22-winter-01/hackathon-22-winter-01_backend pull request #34
Opened 2022-12-15 14:26 UTC by tesso57

全然終わってないけど、とりあえず  `/room/new` だけはやした

2022-12-15 15:07 UTC, ras0q requested changes
ほぼ良さそうだけど少しだけ:pray:

2022-12-15 15:07 UTC, ras0q commented on internal/usecases/repository/repository.go
> +}
正直どっちでもいいんだけどwsとかではRoomRepositoryをそのまま使ってるからRepositoryにまとめずにRoomRepositoryで統一したさがあります
後で変わるかもしれんから何とも言えんけど、、、

2022-12-15 15:07 UTC, ras0q commented on internal/usecases/repository/room.go
>  var CommonRoomID = uuid.New()
このコメントはCommonRoomIDが必要なくなってから消してほしい:pray:

2022-12-15 15:07 UTC, ras0q commented on internal/usecases/repository/repoimpl/room.go
> +	room.Players = append(room.Players, player)
挙動は変わらないけどCreateなのでappendじゃなくて直接要素数1のスライス代入する方が意味的にあってそう

2022-12-16 02:47 UTC, tesso57 commented on internal/usecases/repository/repoimpl/room.go
> +	room.Players = append(room.Players, player)
タシカニ～

2022-12-16 03:57 UTC, ras0q commented
テスト落ちてるのは自分が直しちゃいますね:+1:

2022-12-16 04:27 UTC, ras0q approved these changes
他はよさそう:+1:
自分の変更点も見てほしい:pray:

2022-12-16 05:23 UTC, tesso57 reviewed
バックエンドの知識はないけど、見た感じよさそう。

2022-12-16 05:23 UTC, tesso57 commented on internal/usecases/services/ws/wshandler/card.go
> +	h.sender.Bloadcast(h.room.ID, res)
Bloadcast => Broadcast かも

2022-12-16 05:41 UTC, ras0q commented
マージします

2022-12-16 05:41 UTC, merged

2022-12-16 06:40 UTC, ras0q commented on internal/handler/handler.go
> +	return c.JSON(http.StatusOK, room)
ここに限らずだけどレスポンスは`*domain.Room`じゃなくて`oapi.Room`を返すように構造体を詰め替えてほしい
converter.goってのがあるからそれに詰め替え処理書くと良さ